# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitwave" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "9ceb2a23d0552d1dd3ff03f64c6b80fd3b287cd5ad76b86a07cb80ef591e0966"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a9070a48049edcdc5f1cee49cc3711a1862d0f82a76969e8eed8e8daeb4b472"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4597d84885f891d2333e2024b6fcd7bb369fd94fb95bbafceb20e2471a4ebac4"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b0591fb65698e9dee570181a2ca2b7cb23764d624e3632a1add0ff46c5b7369"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitwave"
  desc "Agent-first accounting platform — run locally, share in the cloud"
  homepage "https://github.com/bitwave-io/bitwave-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bitwave"

  # No zap stanza required

end
