# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitwave" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ebeabb8f1aa3c61a3a60cd8cb5b7e4935c6c96e851b121274041b13da0109f9a"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "386f30dc2e1f9604fcb51686bfde05cc62f36cb0060665b8569ffcf191002d8c"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b72aca73a1edf6fa1b44300936bc4bce01ebd2b8ad8556dee716ead3820aefd"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b2de9c5e726f18c9de80d0b8f587a94e01ebb8c4db6a2dfda72cff2e6719bcd"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitwave"
  desc "Plain-text accounting for humans and agents, by Bitwave"
  homepage "https://github.com/bitwave-io/bitwave-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bitwave"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bitwave"]
    end
  end

  # No zap stanza required

end
