# This file was generated by GoReleaser. DO NOT EDIT.
cask "bitwave" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "52db0c236a96602c4e2b169691a1184b0c2cc579e081a8e8b7d4b17292d3cb94"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6a821687facb2dd6389a77b302d66aeaa15e637875a21f5c37dd7f423bd8258"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe341c61cb970747fc311bfb68b66bc06d1c9c5a13586cf661478024a5c84689"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d2a51056ae76dceb0ed3eaff8f07ffac3597beb8468e6608b79bcec56bf064f"
      url "https://github.com/bitwave-io/bitwave-cli/releases/download/v#{version}/bitwave_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bitwave"
  desc "Agent-first accounting platform — run locally, share in the cloud"
  homepage "https://github.com/bitwave-io/bitwave-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bitwave"

  # No zap stanza required

end
